#cloud-config
# https://pastebin.com/83qc5RGi
rancher:
  services:
    swarm:
      image: swarm
      command: join --advertise $private_ipv4:2375 --heartbeat "10s" --delay "10s" consul://consul.example.internal:8500
      net: host
      privileged: true
      labels:
        io.rancher.os.scope: system
        io.rancher.os.after: docker
    aws-metadata:
      image: deadroot/rancheros-ec2-metadata
      command: -m -t docker. -e example.db.host:DB_HOST -e example.queue.host:QUEUE_HOST
      privileged: true
      labels:
        io.rancher.os.after: network
        io.rancher.os.detach: "false"
        io.rancher.os.scope: system
        io.rancher.os.reloadconfig: "true"
      volumes:
        - /usr/bin/ros:/bin/ros:ro
        - /var/lib/rancher/conf:/var/lib/rancher/conf:rw
    console:
      labels:
        io.rancher.os.after: aws-metadata
  docker:
    args: [daemon, -s, overlay, -G, docker, --cluster-store, consul://consul.example.internal:8500, --cluster-advertise, :2375, -H, unix:///var/run/docker.sock, -H, tcp://0.0.0.0:2375, --userland-proxy=false, --insecure-registry, docker.example.internal:5000]

